import { api } from "@/services/auth";

export type MonitoringType = "process" | "collision" | "market" | "assets";

export type MonitoringProfilePayload = {
  type: MonitoringType;
  name: string;
  clientId?: string;
  assetPatentNumber?: string;
  assetTitle?: string;
  ownerName?: string;
  attorneyName?: string;
  sensitivity?: string;
  scoreMinAlert?: number;
  scoreMinQueue?: number;
  autoGenerateDemand?: boolean;
  sendClientAfterValidation?: boolean;
  feedbackRequired?: boolean;
  channels?: string[];
  tags?: string[];
  rules?: Record<string, unknown>;
  notes?: string;
};

export const monitoringService = {
  getDashboard: async () => {
    const { data } = await api.get(`/monitoring/center/dashboard`);
    return data;
  },
  listProfiles: async (params?: Record<string, unknown>) => {
    const { data } = await api.get(`/monitoring/center/profiles`, { params });
    return data?.rows || [];
  },
  createProfile: async (payload: MonitoringProfilePayload) => {
    const { data } = await api.post(`/monitoring/center/profiles`, payload);
    return data;
  },
  toggleProfile: async (id: string, active: boolean) => {
    const { data } = await api.post(`/monitoring/center/profiles/${id}/toggle`, { active });
    return data;
  },
  listOccurrences: async (params?: Record<string, unknown>) => {
    const { data } = await api.get(`/monitoring/center/occurrences`, { params });
    return data;
  },
  processLatestRpi: async () => {
    const { data } = await api.post(`/monitoring/center/rpi/process-latest`);
    return data;
  },
  processRpi: async (rpiNumber: string) => {
    const { data } = await api.post(`/monitoring/center/rpi/process`, { rpiNumber });
    return data;
  },
  analyzeOccurrenceWithAi: async (id: string) => {
    const { data } = await api.post(`/monitoring/center/occurrences/${id}/analyze-ai`);
    return data;
  },
  applyOccurrenceAction: async (
    id: string,
    action: string,
    payload?: { note?: string; assignee?: string; feedback?: string }
  ) => {
    const { data } = await api.post(`/monitoring/center/occurrences/${id}/action`, {
      action,
      ...(payload || {}),
    });
    return data;
  },
  bulkConvertToDemands: async (occurrenceIds: string[]) => {
    const { data } = await api.post(`/demands/bulk-convert`, { occurrenceIds });
    return data;
  },
  getEmailPreview: async (occurrenceId: string) => {
    const { data } = await api.get(`/monitoring/center/occurrences/${occurrenceId}/email-preview`);
    return data;
  }
};
