import { useMemo, useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Switch } from "@/components/ui/switch";
import { monitoringService, type MonitoringType } from "@/services/monitoring";
import { toast } from "sonner";

type ClientOption = {
  id: string;
  name: string;
};

type Props = {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onCreated: () => Promise<void> | void;
  clients: ClientOption[];
  prefill?: Partial<{
    patentNumber: string;
    title: string;
    clientId: string;
    attorney: string;
    owner: string;
  }>;
};

const monitoringTypeOptions: Array<{ value: MonitoringType; label: string; description: string }> = [
  { value: "process", label: "Monitoramento de Processo", description: "Exigências, anuidades, despachos e marcos processuais." },
  { value: "collision", label: "Monitoramento de Colidência", description: "Comparação entre ativo referência e novas publicações." },
  { value: "market", label: "Monitoramento de Mercado", description: "Movimentos competitivos e sinais tecnológicos." },
  { value: "assets", label: "Meus Ativos", description: "Consolidação de ativos para monitoramentos derivados." },
];

const monitoringTemplates = [
  {
    id: "process-by-number",
    label: "Processo por número",
    type: "process" as MonitoringType,
    seed: { sensitivity: "equilibrado", scoreMinAlert: "60", scoreMinQueue: "75", rulesText: "6.1\n7.1\nanuidade\ndeferimento", tags: "processo, prazo" }
  },
  {
    id: "collision-by-reference",
    label: "Colidência por referência",
    type: "collision" as MonitoringType,
    seed: { sensitivity: "agressivo", scoreMinAlert: "55", scoreMinQueue: "70", rulesText: "palavra-chave principal\nIPC A61B", tags: "colidencia, referencia" }
  },
  {
    id: "market-by-holder",
    label: "Concorrente por titular",
    type: "market" as MonitoringType,
    seed: { sensitivity: "equilibrado", scoreMinAlert: "50", scoreMinQueue: "65", rulesText: "titular: concorrente x\nIPC H04W", tags: "mercado, concorrente" }
  },
  {
    id: "full-asset",
    label: "Ativo completo",
    type: "assets" as MonitoringType,
    seed: { sensitivity: "conservador", scoreMinAlert: "65", scoreMinQueue: "80", rulesText: "ativo principal\nderivar processo\nderivar colidência", tags: "ativos, completo" }
  }
];

export default function NewMonitoringWizard({ open, onOpenChange, onCreated, clients, prefill }: Props) {
  const [step, setStep] = useState(1);
  const [saving, setSaving] = useState(false);
  const [type, setType] = useState<MonitoringType>("process");
  const [name, setName] = useState("");
  const [clientId, setClientId] = useState(prefill?.clientId || "");
  const [assetPatentNumber, setAssetPatentNumber] = useState(prefill?.patentNumber || "");
  const [assetTitle, setAssetTitle] = useState(prefill?.title || "");
  const [ownerName, setOwnerName] = useState(prefill?.owner || "");
  const [attorneyName, setAttorneyName] = useState(prefill?.attorney || "");
  const [sensitivity, setSensitivity] = useState("equilibrado");
  const [scoreMinAlert, setScoreMinAlert] = useState("55");
  const [scoreMinQueue, setScoreMinQueue] = useState("70");
  const [autoGenerateDemand, setAutoGenerateDemand] = useState(false);
  const [sendClientAfterValidation, setSendClientAfterValidation] = useState(false);
  const [feedbackRequired, setFeedbackRequired] = useState(false);
  const [rulesText, setRulesText] = useState("");
  const [tagsText, setTagsText] = useState("");
  const [notes, setNotes] = useState("");

  const typeMeta = useMemo(() => monitoringTypeOptions.find((item) => item.value === type), [type]);

  const reset = () => {
    setStep(1);
    setType("process");
    setName("");
    setClientId(prefill?.clientId || "");
    setAssetPatentNumber(prefill?.patentNumber || "");
    setAssetTitle(prefill?.title || "");
    setOwnerName(prefill?.owner || "");
    setAttorneyName(prefill?.attorney || "");
    setSensitivity("equilibrado");
    setScoreMinAlert("55");
    setScoreMinQueue("70");
    setAutoGenerateDemand(false);
    setSendClientAfterValidation(false);
    setFeedbackRequired(false);
    setRulesText("");
    setTagsText("");
    setNotes("");
  };

  const buildRules = () => {
    const tags = tagsText.split(",").map((item) => item.trim()).filter(Boolean);
    const tokens = rulesText.split("\n").map((item) => item.trim()).filter(Boolean);
    if (type === "process") {
      return {
        processNumbers: assetPatentNumber ? [assetPatentNumber] : [],
        attorneys: attorneyName ? [attorneyName] : [],
        eventFilters: tokens,
        tags,
      };
    }
    if (type === "collision") {
      return {
        patentNumbers: assetPatentNumber ? [assetPatentNumber] : [],
        keywords: tokens,
        ipcCodes: tokens.filter((token) => /\d/.test(token)),
        holders: [],
      };
    }
    if (type === "market") {
      return {
        keywords: tokens,
        holders: tokens.filter((token) => token.includes("titular:")).map((token) => token.replace("titular:", "").trim()),
        ipcCodes: tokens.filter((token) => token.toUpperCase().startsWith("IPC")),
      };
    }
    return {
      patentNumbers: assetPatentNumber ? [assetPatentNumber] : [],
      derivedMonitoring: {
        process: true,
        collision: true,
        market: true,
      },
      tags,
    };
  };

  const submit = async () => {
    if (!name.trim()) {
      toast.error("Defina um nome interno para o monitoramento.");
      return;
    }
    setSaving(true);
    try {
      await monitoringService.createProfile({
        type,
        name: name.trim(),
        clientId: clientId || undefined,
        assetPatentNumber: assetPatentNumber || undefined,
        assetTitle: assetTitle || undefined,
        ownerName: ownerName || undefined,
        attorneyName: attorneyName || undefined,
        sensitivity,
        scoreMinAlert: Number(scoreMinAlert || 55),
        scoreMinQueue: Number(scoreMinQueue || 70),
        autoGenerateDemand,
        sendClientAfterValidation,
        feedbackRequired,
        tags: tagsText.split(",").map((item) => item.trim()).filter(Boolean),
        rules: buildRules(),
        notes: notes || undefined,
      });
      toast.success("Monitoramento criado com sucesso.");
      await onCreated();
      onOpenChange(false);
      reset();
    } catch (error: any) {
      toast.error(error?.response?.data?.error || "Não foi possível criar o monitoramento.");
    } finally {
      setSaving(false);
    }
  };

  const applyTemplate = (templateId: string) => {
    const template = monitoringTemplates.find((item) => item.id === templateId);
    if (!template) return;
    setType(template.type);
    setSensitivity(template.seed.sensitivity);
    setScoreMinAlert(template.seed.scoreMinAlert);
    setScoreMinQueue(template.seed.scoreMinQueue);
    setRulesText(template.seed.rulesText);
    setTagsText(template.seed.tags);
    if (!name.trim()) setName(`Template • ${template.label}`);
    setStep(2);
  };

  return (
    <Dialog
      open={open}
      onOpenChange={(next) => {
        onOpenChange(next);
        if (!next) reset();
      }}
    >
      <DialogContent className="max-w-3xl max-h-[88vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Novo Monitoramento</DialogTitle>
          <DialogDescription>Cadastro guiado para monitorar processo, colidência, mercado ou ativos.</DialogDescription>
        </DialogHeader>

        <div className="space-y-6">
          {step === 1 && (
            <div className="space-y-4">
              <div className="rounded-lg border border-slate-200 bg-slate-50 p-3">
                <p className="text-xs font-semibold text-slate-700 mb-2">Templates prontos</p>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                  {monitoringTemplates.map((template) => (
                    <button key={template.id} onClick={() => applyTemplate(template.id)} className="rounded-md border bg-white px-3 py-2 text-left text-xs hover:border-emerald-300 hover:bg-emerald-50">
                      {template.label}
                    </button>
                  ))}
                </div>
              </div>
              <Label>Tipo de monitoramento</Label>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                {monitoringTypeOptions.map((option) => (
                  <button
                    key={option.value}
                    onClick={() => setType(option.value)}
                    className={`rounded-xl border p-4 text-left transition-colors ${type === option.value ? "border-emerald-400 bg-emerald-50" : "border-slate-200 hover:border-slate-300"}`}
                  >
                    <div className="font-semibold text-slate-900">{option.label}</div>
                    <div className="text-xs text-slate-500 mt-1">{option.description}</div>
                  </button>
                ))}
              </div>
              <div className="flex justify-end">
                <Button onClick={() => setStep(2)}>Continuar</Button>
              </div>
            </div>
          )}

          {step === 2 && (
            <div className="space-y-4">
              <div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm text-slate-700">
                <strong>{typeMeta?.label}:</strong> {typeMeta?.description}
              </div>
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label>Nome interno do monitoramento</Label>
                  <Input value={name} onChange={(e) => setName(e.target.value)} placeholder="Ex: Colidência - Linha bioplástico cliente X" />
                </div>
                <div className="space-y-2">
                  <Label>Cliente</Label>
                  <Select value={clientId || "none"} onValueChange={(value) => setClientId(value === "none" ? "" : value)}>
                    <SelectTrigger>
                      <SelectValue placeholder="Selecione um cliente" />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="none">Sem cliente</SelectItem>
                      {clients.map((client) => (
                        <SelectItem key={client.id} value={client.id}>{client.name}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Número principal</Label>
                  <Input value={assetPatentNumber} onChange={(e) => setAssetPatentNumber(e.target.value)} placeholder="BR102024..." />
                </div>
                <div className="space-y-2">
                  <Label>Ativo / título de referência</Label>
                  <Input value={assetTitle} onChange={(e) => setAssetTitle(e.target.value)} placeholder="Nome curto do ativo monitorado" />
                </div>
                <div className="space-y-2">
                  <Label>Responsável interno</Label>
                  <Input value={ownerName} onChange={(e) => setOwnerName(e.target.value)} placeholder="Analista responsável" />
                </div>
                <div className="space-y-2">
                  <Label>Procurador (quando aplicável)</Label>
                  <Input value={attorneyName} onChange={(e) => setAttorneyName(e.target.value)} placeholder="Escritório ou procurador" />
                </div>
                <div className="space-y-2">
                  <Label>Sensibilidade</Label>
                  <Select value={sensitivity} onValueChange={setSensitivity}>
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="conservador">Conservador</SelectItem>
                      <SelectItem value="equilibrado">Equilibrado</SelectItem>
                      <SelectItem value="agressivo">Agressivo</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label>Score mínimo para alerta</Label>
                  <Input type="number" min={0} max={100} value={scoreMinAlert} onChange={(e) => setScoreMinAlert(e.target.value)} />
                </div>
                <div className="space-y-2">
                  <Label>Score mínimo para triagem</Label>
                  <Input type="number" min={0} max={100} value={scoreMinQueue} onChange={(e) => setScoreMinQueue(e.target.value)} />
                </div>
                <div className="space-y-2 md:col-span-2">
                  <Label>Regras e critérios (1 por linha)</Label>
                  <Textarea value={rulesText} onChange={(e) => setRulesText(e.target.value)} rows={5} placeholder="palavra-chave\nIPC A61B\ntitular: Empresa X\n6.1\n7.1" />
                </div>
                <div className="space-y-2 md:col-span-2">
                  <Label>Tags (separadas por vírgula)</Label>
                  <Input value={tagsText} onChange={(e) => setTagsText(e.target.value)} placeholder="urgente, cliente_a, processo" />
                </div>
                <div className="space-y-2 md:col-span-2">
                  <Label>Observações internas</Label>
                  <Textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={3} />
                </div>
              </div>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
                <div className="rounded-lg border p-3 flex items-center justify-between">
                  <Label>Auto-gerar demanda</Label>
                  <Switch checked={autoGenerateDemand} onCheckedChange={setAutoGenerateDemand} />
                </div>
                <div className="rounded-lg border p-3 flex items-center justify-between">
                  <Label>Enviar cliente após validação</Label>
                  <Switch checked={sendClientAfterValidation} onCheckedChange={setSendClientAfterValidation} />
                </div>
                <div className="rounded-lg border p-3 flex items-center justify-between">
                  <Label>Feedback obrigatório</Label>
                  <Switch checked={feedbackRequired} onCheckedChange={setFeedbackRequired} />
                </div>
              </div>
              <div className="flex justify-between">
                <Button variant="outline" onClick={() => setStep(1)}>Voltar</Button>
                <Button onClick={submit} disabled={saving}>{saving ? "Salvando..." : "Criar monitoramento"}</Button>
              </div>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
